# Generated by Django 2.2 on 2023-12-12 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlepost_total_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='total_views',
        ),
    ]
