# Generated by Django 5.0 on 2023-12-12 12:29

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20231212_1921'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
