# Generated by Django 4.2.8 on 2023-12-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_articlepost_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='tags',
        ),
    ]
